interface CsvAggregationDisaggregationPayloadFields {
  informationReceiverID: string
  informationReceiverContact: string
  informationReceiverEmail: string
  childEPC: string
  informationProviderChild: string
  speciesCodeChild: string
  speciesNameChild: string
  descriptionShortChild: string
  itemConditionCodeChild: string
  itemConditionCodeParent: string
  additionalTradeItemIdentificationParent: string
  aggregationLocation: string
  informationProviderAggregation: string
  nameAggregation: string
  partyIDTypeCodeAggregation: string
  additionalPartyIDAggregation: string
  streetAddressOneAggregation: string
  streetAddressTwoAggregation: string
  cityAggregation: string
  stateAggregation: string
  postalCodeAggregation: string
  countryCodeAggregation: string
  latitudeAggregation: string
  longitudeAggregation: string
  contactAggregation: string
  telephoneAggregation: string
  emailAggregation: string
  disaggregationLocation: string
  informationProviderDisaggregation: string
  nameDisaggregation: string
  partyIDTypeCodeDisaggregation: string
  additionalPartyIDDisaggregation: string
  streetAddressOneDisaggregation: string
  streetAddressTwoDisaggregation: string
  cityDisaggregation: string
  stateDisaggregation: string
  postalCodeDisaggregation: string
  countryCodeDisaggregation: string
  latitudeDisaggregation: string
  longitudeDisaggregation: string
  contactDisaggregation: string
  telephoneDisaggregation: string
  emailDisaggregation: string
  eventTime: string
  eventTimeZoneOffset: string
  parentEPC: string
  readPointAggregation: string
  bizLocationAggregation: string
  quantity: string
  uom: string
  productOwner: string
  informationProvider: string
  readPointDisaggregation: string
  bizLocationDisaggregation: string
  informationProviderID: string
  informationProviderContact: string
  informationProviderEmail: string
}
