interface CsvAggregationDisaggregationPayloadFields {
  informationProviderID: string
  informationProviderContact: string
  informationProviderEmail: string
  informationReceiverID: string
  informationReceiverContact: string
  informationReceiverEmail: string
  childEPC: string
  informationProviderChild: string
  speciesCodeChild: string
  speciesNameChild: string
  descriptionShortChild: string
  itemConditionCodeChild: string
  parentEPC: string
  informationProviderParent: string
  descriptonShortParent: string
  speciesCodeParent: string
  speciesNameParent: string
  preservationTechniqueCode: string
  unitOfMeasure: string
  grossWeight: string
  itemConditionCodeParent: string
  additionalTradeItemIdentificationParent: string
  location: string
  name: string
  partyIDTypeCode: string
  additionalPartyID: string
  streetAddressOne: string
  streetAddressTwo: string
  city: string
  state: string
  postalCode: string
  countryCode: string
  latitude: string
  longitude: string
  contact: string
  telephone: string
  email: string
  action: string
  eventTime: string
  eventTimeZoneOffset: string
  readPoint: string
  bizLocation: string
  purchaseOrderNumber: string
  quantity: string
  productOwner: string
  informationProvider: string
}
