interface CsvShipReceivePayloadFields {
  informationProviderID: string
  informationProviderContactName: string
  informationProviderEmail: string
  destinationID: string
  destinationContactName: string
  destinationEmail: string
  shipFromParty: string
  informationProvider: string
  shipFromPartyOwnerName: string
  shipFromPartyAddress1: string
  shipFromPartyAddress2: string
  shipFromPartyCity: string
  shipFromPartyCountry: string
  shipFromPartyPostalCode: string
  shipFromPartyState: string
  shipFromPartyCountryCode: string
  shipFromPartyContactName: string
  shipFromPartyContactEmail: string
  shipToParty: string
  shipToPartyOwnerName: string
  shipToPartyAddress1: string
  shipToPartyAddress2: string
  shipToPartyCity: string
  shipToPartyCountry: string
  shipToPartyPostalCode: string
  shipToPartyState: string
  shipToPartyCountryCode: string
  shipToPartyContactName: string
  shipToPartyContactEmail: string
  shipFromLocation: string
  shipFromLocationOwnerName: string
  shipFromLocationAddress1: string
  shipFromLocationAddress2: string
  shipFromLocationCity: string
  shipFromLocationCountry: string
  shipFromLocationPostalCode: string
  shipFromLocationState: string
  shipFromLocationCountryCode: string
  shipToLocation: string
  shipToLocationOwnerName: string
  shipToLocationAddress1: string
  shipToLocationAddress2: string
  shipToLocationCity: string
  shipToLocationCountry: string
  shipToLocationPostalCode: string
  shipToLocationState: string
  shipToLocationCountryCode: string
  eventTimeV1: string
  eventTimeZoneOffsetV1: string
  palletId: string
  readPoint1: string
  bizLocation1: string
  po: string
  invoice: string
  certificate: string
  legalEntitySellingProduct: string
  eventTimeV2: string
  eventTimeZoneOffsetV2: string
  legalEntityBuyingProduct: string
}
